### ISSUE TITLE
Reference is outdated

### ISSUE THREAD

**Issue by ThomasDeLange** [PlaceNL/Orders#2]
Kan de reference.png aangepast worden? De bot gaat nu over bestaande artwork heen.

**Comment by IntangibleMatter** [comment]
In addition to this there are talks of the Moon Berry being approved. Would I be able to edit this image to add it?

**Comment by NoahvdAa** [comment]
Deze repo is vervangen door ons nieuwe Commando systeem. Voor wijzigingsverzoeken, neem contact met ons op via de Discord server.

This repo has been replaced by our new Commando system. Please contact us in the discord server for change requests.
